use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'UIComponents_Example' do
  pod 'UIComponents', :path => '../'

  target 'UIComponents_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    
    pod 'AutoModel'
    pod 'NFAToolkit'
    pod 'SwiftProjects'
    pod 'SnapKit'  , '~> 4.2.0'
#    pod 'SDWebImage'  , '~>  5.5.2'
    pod 'ProThirdpart'
    
  end
end
